config/routes.rb
Rails.application.routes.draw do
  resources :registered_applications

  devise_for :users

  get 'about' => 'welcome#about'

  authenticated :user do
    root to: 'registered_applications#index', as: :authenticated_root, via: :get
  end

  unauthenticated do
    root to: 'welcome#index'
  end

  namespace :api, defaults: { format: :json } do
    match 'create_event', to: 'events#create', via: [:options]
    resources :events, only: [:create]
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events

  validates :name, presence: true
  validates :url, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController

  before_filter :set_access_control_headers
  skip_before_action :verify_authenticity_token

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if !registered_application
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = registered_application.events.new(event_params)
      if @event.save
        render json: @event, status: :created
      else
        render @event.errors, status: :unprocessable_entity
      end
    end
  end

  private

  def event_params
    Rails.logger.info "\n\nparams: #{params}\n\n"
    params.require(:event).permit(:name)
  end

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Access-Control-Allow-Origin, Content-Type'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_registered_application, only: [:show, :edit, :update, :destroy]
  
  def index
    @registered_applications = current_user.registered_applications.all
  end

  def show
    @events = @registered_application.events.group_by(&:name)
  end

  def new
    @registered_application = RegisteredApplication.new  
  end

  def create
    @registered_application = current_user.registered_applications.new(registered_application_params)
    if @registered_application.save
      flash[:notice] = "Application was saved successfully."
      redirect_to registered_applications_path
    else
      flash[:error] = "Error creating application. Please try again."
      render :new
    end  
  end
  
  def edit    
  end
  
  def update
    if @registered_application.update_attributes(registered_application_params)
      flash[:notice] = "Application was updated successfully."
      redirect_to registered_applications_path
    else
      flash[:error] = "Error saving application. Please try again."
      render :edit
    end    
  end
  
  def destroy
    name = @registered_application.name  
    if @registered_application.destroy
      flash[:notice] = "#{name} was deleted successfully."
      redirect_to registered_applications_path
    else
      flash[:error] = "There was an error deleting the application. Please try again."
      render :show
    end    
  end
  
  private
  
  def set_registered_application
    @registered_application = RegisteredApplication.find(params[:id])
  end
  
  def registered_application_params
    params.require(:registered_application).permit(:name, :url)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs"> 
      <li><%= link_to "Blocmetrics", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= current_user.email %>! <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or 
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>

    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>

</body>
</html>

app/views/registered_applications/_form.html.erb
<% if current_user %>
  <div class="col-md-8">
    <%= form_for registered_application do |f| %>
      <% if registered_application.errors.any? %>
      <div class="alert alert-danger">
        <h4>There are <%= pluralize(registered_application.errors.count, "error") %>.</h4>
        <ul>
          <% registered_application.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.url_field :url, class: 'form-control', placeholder: "Enter the applications url" %>
      </div>
      <div class="form-group">
        <%= f.submit "Register Application", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/registered_applications/edit.html.erb
<h1>Edit Application</h1>

<div class="container">
  <%= render partial: 'form', locals: { registered_application: @registered_application } %>
</div>

<%= link_to 'Show', registered_application_path(@registered_application) %>
<%= link_to 'Back', registered_applications_path %>

app/views/registered_applications/index.html.erb
<h1>Registered Applications</h1>
<div class='row'>
  <div class='col-md-8'>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Application Name</th>
          <th>Application URL</th>
          <th>Actions</th>
        </tr>
      </thead>
    <% @registered_applications.each do |application| %>
      <tr>
        <td><strong><%= link_to application.name, application %></strong></td>
        <td><%= link_to application.url, application.url, target: "_blank" %></td>
        <td>
          <%= link_to 'Show', registered_application_path(application), class: 'btn btn-success' %>
          <%= link_to 'Edit', edit_registered_application_path(application), class: 'btn btn-success' %>
          <%= link_to 'Delete', registered_application_path(application), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this application?' } %>
        </td>
      </tr>
    <% end %>
    </table>
    <%= link_to "Add new application", new_registered_application_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/registered_applications/new.html.erb
<div class="row">
  <h4>Add a New Application to Track</h4>
  <%= render partial: 'form', locals: { user: @user, registered_application: @registered_application } %>
</div>

app/views/registered_applications/show.html.erb
<%= javascript_include_tag "//www.google.com/jsapi" %>
<%= javascript_include_tag "application", "chartkick" %>
<%= yield :charts_js %>

<div class="row">
  <div class="col-md-8">
    <h1><%= @registered_application.name %></h1>
    <h4><%= link_to @registered_application.url, @registered_application.url, target: "_blank" %></h4>
  </div>
  <div class="col-md-4">
    <%= link_to "Unregister Application", @registered_application, method: :delete, data: { confirm: "Are you sure you want to unregister this application? This process is unreversible!" }, class: 'btn btn-danger' %>
</div>

<table class="table table-bordered table-hover">
  <thead>
    <th>Event Name</th>
    <th>Event Count</th>
  </thead>
  <tbody>
    <% @events.each do |name, event| %>
    <tr>
      <td><%= name %></td>
      <td><%= event.count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= pie_chart @registered_application.events.group(:name).count %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Blocmetrics</h1>
  <p>Blocmetrics is an analytics service and reporting tool that you can use with web apps to track user activity and report results.</p>
  <p>
    <%= link_to "Sign in", new_user_session_path, class: 'btn btn-primary' %> or
    <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Reporting Features</h2>
    <p>Become more aware of which parts or your application users are utilizing the most!
  </div>
  <div class="col-md-4">
    <h2>API</h2>
    <p>Easy to use API to allow you to format your data the way you'd like! You can integrate the analytics into your existing application and workflow!</p>
  </div>
  <div class="col-md-4">
    <h2>Tracking</h2>
    <p>Provides an easy and efficient way for you to track user activity.</p>
  </div>
</div>